### ISSUE TITLE
Oauth2 Azure AD v2 Endpoint and MFA

### ISSUE THREAD

**Issue by achawkins** [marknadig/omniauth-azure-oauth2#28]
My organization uses MFA through our SSO in Azure AD. For whatever reason, I am not prompted for MFA when accessing the `v1` endpoint (`/<tenant>/oauth2/authorize`). When I manually change this to the `v2` endpoint (`/<tenant>/oauth2/v2.0/authorize`) and add a scope such as `User.Read`, I am prompted for MFA.

I can probably make this change, and submit a PR, but I am not very familiar with Ruby and do not have much time right now. If someone would like to add the `v2` endpoint, I would be very grateful.

**Comment by achawkins** [comment]
https://github.com/KonaTeam/omniauth-azure-oauth2/pull/30

**Comment by KatharineArnold** [comment]
Hello, I also need to use v2 endpoints.  Any chance this can get merged in soon?

**Comment by marknadig** [comment]
Sure wish I had time to maintain this, but I don't :/. Best bet is to fork this. Perhaps someone will publish their fork on RubyGems.
